# Generated by Django 5.1.1 on 2025-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0004_alter_parent_father_mobile_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="clubs",
            field=models.ManyToManyField(
                blank=True, related_name="members", to="student.club"
            ),
        ),
    ]
